### PR TITLE
24w21a changes

### PR DESCRIPTION
**Pull request by neylz**
Edit the Core shader list following the changes bringt by 24w21a

https://www.minecraft.net/en-us/article/minecraft-snapshot-24w21a
image

### CODE REVIEW

**Review by McTsts — APPROVED** [review]
dont think it makes much of a difference but I updated the image's name to match the shader name it belongs to now

**Comment by neylz** [comment]
yea, good idea. Just renaming it to `position_tex_color_2` to keep file naming consitent ;)

**Comment by neylz** [comment]
should we also rename `wall_overlay.png` to `position_tex_color_3.png` on the fly?

**Comment by McTsts** [comment]
Ah dang I didnt see the _ in the file name. wall overlay seems to be the only other one not fitting the pattern? yeah then it should be renamed too

**Pull request merged**
